//
// Created by jiale on 2020/10/3.
//

#ifndef I3_SWITCH_NOTIFICATION_CONSTS_H
#define I3_SWITCH_NOTIFICATION_CONSTS_H

const int MICROSECOND_UNIT = 1000 * 1000;

#endif  //I3_SWITCH_NOTIFICATION_CONSTS_H
